package expo.modules.rhythmdevice

object RhythmNativePolicyKeys {
    const val PREFS = "rhythm_native_policy"
    const val BASE_RESTRICTED_PACKAGES = "base_restricted_packages"
    const val ACCESS_LEASES_JSON = "access_leases_json"
    const val EXTRA_PACKAGE_NAME = "extra_package_name"
    const val RISK_GROUP_POLICIES_JSON = "risk_group_policies_json"
    const val GROUP_USAGE_LEDGER_JSON = "group_usage_ledger_json"
    const val LAST_USAGE_RECONCILED_AT = "last_usage_reconciled_at"
    const val LAST_USAGE_ACCOUNTED_AT = "last_usage_accounted_at"
    const val LAST_USAGE_ACCOUNTED_BY_PACKAGE_JSON = "last_usage_accounted_by_package_json"
    const val ROUTINE_SCHEDULE_JSON = "routine_schedule_json"
    const val COOLDOWN_POLICIES_JSON = "cooldown_policies_json"
    const val ATTENTION_POLICY_JSON = "attention_policy_json"
    const val ATTENTION_EXCHANGE_STATE_JSON = "attention_exchange_state_json"
    const val READING_GATES_JSON = "reading_gates_json"
    const val DAILY_READING_EVIDENCE_JSON = "daily_reading_evidence_json"
    const val EXTRA_GROUP_ID = "extra_group_id"
    const val EXTRA_GROUP_NAME = "extra_group_name"
    const val EXTRA_COOLDOWN_ENDS_AT = "extra_cooldown_ends_at"
    const val EXTRA_ACTIVITY_TITLE = "extra_activity_title"
    const val EXTRA_ACTIVITY_SUBTITLE = "extra_activity_subtitle"
    const val EXTRA_ACTIVITY_EMOJI = "extra_activity_emoji"
    const val EXTRA_ACTIVITY_DURATION = "extra_activity_duration"
    const val EXTRA_INTERVENTION_MODE = "extra_intervention_mode"
    const val EXTRA_ATTENTION_ORDINAL = "extra_attention_ordinal"
    const val EXTRA_REQUIRED_READING_SECONDS = "extra_required_reading_seconds"
    const val EXTRA_REQUIRED_QUALIFIED_PAGES = "extra_required_qualified_pages"
    const val EXTRA_VERIFIED_ACTIVE_SECONDS = "extra_verified_active_seconds"
    const val EXTRA_VERIFIED_QUALIFIED_PAGES = "extra_verified_qualified_pages"
    const val EXTRA_REMAINING_READING_SECONDS = "extra_remaining_reading_seconds"
    const val EXTRA_REMAINING_QUALIFIED_PAGES = "extra_remaining_qualified_pages"
    const val EXTRA_READER_PROVIDER_AVAILABLE = "extra_reader_provider_available"
    const val EXTRA_READER_PROTOCOL_COMPATIBLE = "extra_reader_protocol_compatible"
    const val EXTRA_READER_APP_AVAILABLE = "extra_reader_app_available"
}

